[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openweather-sdk"
version = "0.1.0"
description = "SDK para OpenWeatherMap - Desafio Técnico Caiena"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["requests>=2.32.0"]

[project.optional-dependencies]
test = ["pytest>=8.0.0", "responses>=0.25.0"]
example = ["python-dotenv>=1.0.0"]

[tool.setuptools.packages.find]
where = ["src"]